export const CHANGE_SITENAME="CHANGE_SITENAME";
export const POSTS_SET="POSTS_SET";
export const SELECT_POST="SELECT_POST";
export const GET_COMMENTS="GET_COMMENTS";
export const RESET_POST_DETAILS="RESET_POST_DETAILS";
